{% set name = "autogluon.common" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  # sha256: 96075e9bfce79420fe78a5566a1ba82f9a80598e955f4a4fc490f5561ede70bd
  # Use the latest commit temporarily
  url: https://github.com/autogluon/autogluon/archive/1f9f043fc03a878abca98a7abc5994e6ec82a0ab.tar.gz
  sha256: e1b29936eeab8f1a4298696598a13cc342db661f8c1d6490b969c85ca8d40469

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./common -vv
  number: 3
  script_env:
   - RELEASE=1

requirements:
  host:
    - python >=3.8,<3.11
    - pip
  # see https://github.com/autogluon/autogluon/blob/master/core/src/autogluon/core/_setup_utils.py
  run:
    - python >=3.8,<3.11
    - numpy >=1.21,<1.27
    - pandas >=1.4.1,<1.6
    - boto3 >=1.10,<2
    - psutil >=5.7.3,<6
    - setuptools

test:
  imports:
    - autogluon.common
  commands:
    - python -c "from autogluon.common import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon.common
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
    - Innixma
    - sxjscience
    - gradientsky
